name: tadawal
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  fluttertoast: ^8.1.1
  font_awesome_flutter: ^10.3.0
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  dio: ^4.0.6
  floor: ^1.3.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - lang/ar.json
    - lang/en.json
    - assets/images/


  fonts:
    - family: Cairo
      fonts:
          - asset: assets/fonts/Cairo/static/Cairo-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/Cairo/static/Cairo-Light.ttf
            weight: 300
          - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
            weight: 400
          - asset: assets/fonts/Cairo/static/Cairo-Medium.ttf
            weight: 500
          - asset: assets/fonts/Cairo/static/Cairo-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
            weight: 700
          - asset: assets/fonts/Cairo/static/Cairo-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Cairo/static/Cairo-Black.ttf
            weight: 900

